spring:
  application:
    name: ledgerly-api
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
server:
  address: 0.0.0.0
  port: 8080