version: '3'
services:
  db:
    image: postgres:latest
    container_name: ledgerly-db
    environment:
      POSTGRES_USER: ledgerly_user
      POSTGRES_PASSWORD: ledgerly123
      POSTGRES_DB: ledgerly
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/
  backend:
    build:
      context: ./ledgerly-api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/ledgerly
      - SPRING_DATASOURCE_USERNAME=ledgerly_user
      - SPRING_DATASOURCE_PASSWORD=ledgerly123
      - JWT_SECRET_KEY="dGVzdHRyYWNrbHVja3ljdXR0aW5ndGhlb3J5Y2hlZXNlc3RvY2t2ZXJ5aHVycmllZGJpY3ljbGVoYXJkZXJzdA=="
volumes:
  db-data: {}